/* eslint-disable react/jsx-key */
import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { NextPage } from 'next/types'
import styles from '../../../styles/Home.module.css'
import { useRouter } from 'next/router'



export const User: NextPage = () => {
  const router = useRouter();
  const {userId} = router.query

  const [user, setUser] = useState<any>();
  const [lists, setLists] = useState<any>();

  useEffect(() => {
    if (!userId) {
      return
    }
    const fetchUserData = async () => {
      const userData = await fetch(`/api/sanity/users/${userId}`);
      const userLists = await fetch(`/api/sanity/users/${userId}/lists`);
      setUser(await userData.json());
      setLists(await userLists.json());
    };
    fetchUserData();
  }, [userId]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to My Wish List
        </h1>

        <div className={styles.grid}>
          User ID: {userId}
          <div>{JSON.stringify(user)}</div>
          Lists:
          <div>{JSON.stringify(lists)}</div>
          
          {/*productData.map((product: any) => <OgProduct {...product} />)*/}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


// export const getStaticProps: GetStaticProps<{}, ListParams> = async () => {

//   const sanityClient = getClient();
  
//   const products = await sanityClient.fetch(getAllPRoductsQuery);

//   const productPromieses = Promise.all(products.map(async (product: any) => {
//     const og = await scrape(product.url);
//     const origin = new URL(product.url).origin;
//     return {
//       ...product,
//       ...og,
//       origin
//     }
//   }))

//   const productData = await productPromieses;

//   return {
//     props: {
//       productData
//     }
//   }
// }

export default User;
