/* eslint-disable react/jsx-key */
import Head from 'next/head'
import Image from 'next/image'
import { GetStaticProps, NextPage } from 'next/types'
import { getClient } from '../services/sanity/client'
import { OgProduct } from '../components/og/Product'
import { getAllPRoductsQuery } from '../services/sanity/queries/product'
import { scrape } from '../services/scraper'
import styles from '../styles/Home.module.css'

type HomePageProps = {
  productData: any
}

export const Home: NextPage<HomePageProps> = ({productData}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to My Wish List
        </h1>

        <div className={styles.grid}>
          {productData.map((product: any) => <OgProduct {...product} />)}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps: GetStaticProps<{}> = async () => {

  const sanityClient = getClient();
  
  const products = await sanityClient.fetch(getAllPRoductsQuery);

  const productPromieses = Promise.all(products.map(async (product: any) => {
    const og = await scrape(product.url);
    return {
      ...product,
      ...og
    }
  }))

  const productData = await productPromieses;

  return {
    props: {
      productData
    }
  }
}

export default Home;
